homeassistant:
  # Name of the location where Home Assistant is running
  name: Casa
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 95
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Rome
  #URL
  #external_url: !secret external_url
  internal_url: http://localhost:8123
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages


#logger:
#  default: info
#  logs:
#    homeassistant.automations: debug

# Discovery
ssdp:

zeroconf:

# Enables python scripts
python_script:

favicon:
  title: HA Core Test
  icon_path: /local/favicons/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

recorder:

history:


# Systetm Health
system_health:

# MQTT
mqtt:
  broker: 192.168.1.10
  port: 1883
  username: !secret mosquitto_user
  password: !secret mosquitto_passwd
  client_id: home-assistant-ubuntu
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'hass-ubuntu/status'
    payload: 'online'
  will_message:
    topic: 'hass-ubuntu/status'
    payload: 'offline'
  
# api
api:

# webhook
webhook:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'
    cache_dir: /tmp/tts
  
#tts:
#- platform: google_cloud
#  key_file: TTS_Home Assistant-f3f48b89caf0.json
#  language: it-IT
#  gender: female
#  voice: it-IT-Standard-B
  
# TADO
#tado:
#  username: !secret tado_user
#  password: !secret tado_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_selects.yaml
sensor: !include sensors.yaml
light: !include lights.yaml

