homeassistant:
  name: Casa
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 95
  unit_system: metric
  time_zone: Europe/Rome
  #external_url: !secret external_url
  internal_url: !secret internal_url 
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - "/home/snakuzzo/.homeassistant"


#http:
#  ssl_certificate: /home/snakuzzo/ssl/fullchain.pem
#  ssl_key: /home/snakuzzo/ssl/privkey.pem
#logger:
#  default: info
  #logs:
    #homeassistant.components.automations: debug
  #  homeassistant.bootstrap: info
logbook:

# Discovery
ssdp:

zeroconf:

# Enables python scripts
python_script:

favicon:
  title: HA Core Test
  icon_path: /local/favicons/

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

recorder:

history:

upnp:
  local_ip: 192.168.1.30
  
# Systetm Health
system_health:

# MQTT
mqtt:
  broker: !secret mosquitto_ip
  port: !secret mosquitto_port
  username: !secret mosquitto_user
  password: !secret mosquitto_passwd
  client_id: !secret mosquitto_client
  keepalive: 60
  discovery: true
  discovery_prefix: !secret mosquitto_ha_discovery_topic
  birth_message:
    topic: !secret mosquitto_lwt
    payload: 'online'
    retain: true
    qos: 1
  will_message:
    topic: !secret mosquitto_lwt
    payload: 'offline'
    retain: true
    qos: 1

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

# api
api:

# webhook
webhook:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'it'
    cache_dir: /tmp/tts
  
#tts:
#- platform: google_cloud
#  key_file: TTS_Home Assistant-abc123d13f0.json
#  language: it-IT
#  gender: female
#  voice: it-IT-Standard-B

shopping_list:

stream:
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
input_select: !include input_selects.yaml
sensor: !include sensors.yaml
light: !include lights.yaml

