- platform: mqtt
  name: "Luce Camera"
  state_topic: "stat/sonoff-camera/RESULT"
  value_template: "{{ value_json.POWER }}"
  command_topic: "cmnd/sonoff-camera/POWER"
  availability_topic: "tele/sonoff-camera/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: false
