- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

- platform: command_line
  name: Latest Tasmota Version
  command: 'curl https://api.github.com/repos/arendst/Tasmota/releases/latest -s | jq .name -r'
  scan_interval: 30
  value_template: "{{ value.split()[1] | replace('v','') }}"