blueprint:
  name: Esempio Luce Presenza
  description: Accende la luce quando viene rilevata presenza da un sensore
  domain: automation
  input:
    motion_sensor:
      name: Sensore di presenza
      description: Sensore che farà spegnere o accendere la luce
      selector:
        entity:
          domain: binary_sensor
          device_class: motion
    target_light:
      name: Luci
      description: Luci da pilotare
      selector:
        target:
          entity:
            domain: light

trigger:
  platform: state
  entity_id: !input motion_sensor

action:
  service: >
    {% if trigger.to_state.state == "on" %}
      light.turn_on
    {% else %}
      light.turn_off
    {% endif %}
  data:
    entity_id: !input target_light