# timer per gestire l'intervallo di tempo
timer:

  automazione_finale:
    duration: '00:00:10'  # intervallo di tempo


# Automazione per gestire l'impostazione di T0
automation:

- alias: Imposta timer
  trigger:
  # Quando parte Homeassistant
  - platform: homeassistant
    event: start    
  # Oppure quando viene attivata l'automazione
  - platform: state
    entity_id: automation.automazione_finale
    to: 'on'
  action:
  # ...invio una notifica per segnalare l'avvio del timer
  - service: persistent_notification.create
    data:
      title: 'Timer'
      message: 'Timer partito per la prima volta'
  # ...e faccio partire il timer 
  - service: timer.start
    data:
      entity_id: timer.automazione_finale

# Automazione da eseguire al termine di ogni intervallo di tempo
- alias: Automazione Finale
  trigger:
  # Quando il timer finisce
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.automazione_finale
  action:
  # ...faccio ripartire il timer
  - service: timer.start
    data:
      entity_id: timer.automazione_finale
  # ...e mando una notifica per segnalare che è stato restartato il timer
  - service: persistent_notification.create
    data:
      title: 'Automazione Finale'
      message: 'Timer restartato'

# Nel momento in cui si disattiva l'automazione finale da GUI, ovviamente il timer finisce ma non viene eseguito nulla
# Quando si riattiva l'automazione da GUI...sarà quello il T0 ed il timer partirà automaticamente