input_number:
  temperatura_scialla:
    initial: 25
    min: 16
    max: 30
    step: 1
    mode: box

sensor:
  - platform: template
    sensors:
      hygrothermograph_temperature:
        value_template: "{{ states('input_number.temperatura_scialla') }}"
      
automation:

- alias: 'Prova Diego'
  trigger:
  # l'automazione scatta all'ora indicata
  - platform: time
    at: '06:30:00'
  # ...oppure se la temperatura è superiore a 29°C per 5 min
  - platform: numeric_state
    entity_id: sensor.hygrothermograph_temperature
    below: 29
    for:
      minutes: 5
  # ...oppure se la temperatura è superiore a 29°C per 5 min    
  - platform: numeric_state
    entity_id: sensor.hygrothermograph_temperature
    above: 29
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
    # solo se è verificata una delle seguenti condizioni
    # PRIMA CONDIZIONE
    - condition: and
      conditions:
      # se il trigger è stato di tipo numeric_state ed il valore è > 29
      - condition: template
        value_template: "{{ trigger.platform == 'numeric_state' and trigger.to_state.state | float > 29 }}"
      # ...e scialla è a casa
      - condition: state
        entity_id: 'device_tracker.life360_scialla'
        state: 'home'
      # ...e siamo nella fascia oraria 00:00 - 06:30
      - condition: time
        after: '00:00:00'
        before: '06:30:00'
    # SECONDA CONDIZIONE
    - condition: or
      conditions: 
      # se il trigger è di tipo numeric_state ed il valore è < 29
      - condition: template
        value_template: "{{ trigger.platform == 'numeric_state' and trigger.to_state.state | float < 29 }}"
      # ...oppure se il trigger è di tipo time 
      - condition: template
        value_template: "{{ trigger.platform == 'time' }}"
  action:
  # 1. Se il trigger è di tipo time manda il turn_off.
  #    NOTA: Non è necessario verificare che il ventilatore si acceso...
  #    ...al massimo manda un turn_off di un qualcosa che è già off
  # 2. Se il trigger non è di tipo time dev'essere per forza di tipo numeric_state
  #    ...quindi verifico solo il valore. Se è superiore a 29 manda il turn_on
  # 3. Infine, nell'else puoi trovarti solo nella condizione in cui il platform è
  #    ...di tipo numeric_state ed ha un valore inferiore a 29. Quindi manda il turn_off
  - service_template: >
      {% if trigger.platform == 'time'  %}
        fan.turn_off
      {% elif trigger.to_state.state | float > 29 %}
        fan.turn_on
      {% else %}
        fan.turn_off
      {% endif %}
    data:
      entity_id: fan.ventilatore_letto
    
  
