automation:

- alias: 'System - Set Custom Theme at Startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: 'Google Dark Theme 1.9'