automation:

- alias: AvvisoIndiferenziatoUmido 
  description: Avviso tramite google mini di mettere fuori scovazze la sera prima della raccolta 
  trigger:
  - platform: time
    at: "17:26:00"
  #condition:
  #- condition: numeric_state
  #  entity_id: sensor.temperature
  #  above: 0
  #  below: 2
  #  value_template: "{{ state_attr('sensor.indifferenziato','days') }}"
  action:
  - service: tts.google_say
    data: 
      entity_id: media_player.friday 
      message: Buonasera! Ricordiamoci dei rifiuti!
  - delay: "00:00:05"
  - service: media_player.turn_off
    data:
      entity_id: media_player.friday 