input_select:
  stato_faro_piazzale:
    name: 'Stato faro'
    options:
      - SPENTO
      - ACCESO
    initial: SPENTO  
    icon: mdi:flash      
  setta_inizio_piazzale:
    name: 'Ora inizio'
    options:
      - "06:00"
      - "21:00"      
      - "17:00"
      - "21:30"      
  setta_fine_piazzale:
    name: 'Ora fine'
    options:
      - "06:00"
      - "21:00"      
      - "21:30"
      - "22:00"

automation:
- alias: 'Accendi programmazione faro piazzale'
  trigger:
  - entity_id: input_select.stato_faro_piazzale
    platform: state
    to: ACCESO
  action:
  - condition: template
    value_template: '{{ states.input_select.setta_inizio_piazzale.state != states.input_select.setta_fine_piazzale.state }}'
  - entity_id: automation.programma_inizio_faro_piazzale
    service: automation.turn_on