input_number:

  scaldino_bagno_duration:
    name: Durata
    initial: 5
    min: 5
    max: 59
    step: 1

automation:

- alias: automation alias (name)
  trigger:
  - event: start
    platform: homeassistant
  action:
  - delay: "00:{{ states('input_number.scaldino_bagno_duration') | int }}:00"    