automation:

- alias: Republish with retain WDS1
  trigger:
  - platform: mqtt
    topic: 'tele/Brige1T/RESULT'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E47A0A" }}'
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E47A0E" }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: tele/wds1/SENSOR
      payload: "{{ trigger.payload }}"
      retain: true

- alias: Republish with retain WDS2
  trigger:
  - platform: mqtt
    topic: 'tele/Brige1T/RESULT'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E60D0A" }}'
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E60D0E" }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: tele/wds2/SENSOR
      payload: "{{ trigger.payload }}"
      retain: true

- alias: Republish with retain WDS3
  trigger:
  - platform: mqtt
    topic: 'tele/Brige1T/RESULT'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "21280A" }}'
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "21280E" }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: tele/wds3/SENSOR
      payload: "{{ trigger.payload }}"
      retain: true

- alias: Republish with retain WDS4
  trigger:
  - platform: mqtt
    topic: 'tele/Brige1T/RESULT'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E0ED0A" }}'
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E0ED0E" }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: tele/wds4/SENSOR
      payload: "{{ trigger.payload }}"
      retain: true

- alias: Republish with retain WDS5
  trigger:
  - platform: mqtt
    topic: 'tele/Brige1T/RESULT'
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E6690A" }}'
    - condition: template
      value_template: '{{ trigger.payload_json["RfReceived"].Data == "E6690E" }}'
  action:
  - service: mqtt.publish
    data_template:
      topic: tele/wds5/SENSOR
      payload: "{{ trigger.payload }}"
      retain: true

binary_sensor:

  - platform: mqtt
    name: 'WDS1'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    state_topic: "tele/wds1/SENSOR"
    value_template: >-
      {% if value_json['RfReceived'].Data == 'E47A0A' %}
        on
      {% elif value_json['RfReceived'].Data == 'E47A0E' %}
        off
      {% endif %}

  - platform: mqtt
    name: 'WDS2'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    state_topic: "tele/wds2/SENSOR"
    value_template: >-
      {% if value_json['RfReceived'].Data == 'E60D0A' %}
        on
      {% elif value_json['RfReceived'].Data == 'E60D0E' %}
        off
      {% endif %}

  - platform: mqtt
    name: 'WDS3'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    state_topic: "tele/wds3/SENSOR"
    value_template: >-
      {% if value_json['RfReceived'].Data == '21280A' %}
        on
      {% elif value_json['RfReceived'].Data == '21280E' %}
        off
      {% endif %}

  - platform: mqtt
    name: 'WDS4'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    state_topic: "tele/wds4/SENSOR"
    value_template: >-
      {% if value_json['RfReceived'].Data == 'E0ED0A' %}
        on
      {% elif value_json['RfReceived'].Data == 'E0ED0E' %}
        off
      {% endif %}

  - platform: mqtt
    name: 'WDS5'
    payload_on: 'on'
    payload_off: 'off'
    device_class: door
    state_topic: "tele/wds5/SENSOR"
    value_template: >-
      {% if value_json['RfReceived'].Data == 'E6690A' %}
        on
      {% elif value_json['RfReceived'].Data == 'E6690E' %}
        off
      {% endif %}
 