input_boolean: 
  dummy: 
    name: sensore_porta 
    initial: off

binary_sensor:
- platform: template 
  sensors: 
    sensore_porta:
      friendly_name: sensore # IR scala 
      device_class: motion 
      value_template: "{{ is_state('input_boolean.dummy', 'on') }}"   
      delay_off: 
        seconds: 10