########################

input_number:
  dummy_temperature:
    name: "Temperature"
    min: 18
    max: 30
    step: 0.1
    
input_boolean:
  away_switch:
    name: "Away"
  dummy_switch:
    name: "Switch"
  dummy_cover_switch_open:
    name: "Open Cover"
  dummy_cover_switch_close:
    name: "Close Cover"
  
# SENSORE TEMPERATURA
sensor:
  - platform: template
    sensors:
      dummy_temperature:
        friendly_name: "Temperature"
        value_template: "{{ states('input_number.dummy_temperature') | float(2) }}"

# SWITCH
switch:

- platform: template
  switches:
    dummy_switch:
      friendly_name: "Switch"
      value_template: "{{ is_state('input_boolean.dummy_switch','on') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.dummy_switch
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.dummy_switch
    dummy_cover_switch_open:
      friendly_name: "Open Cover"
      value_template: "{{ is_state('input_boolean.dummy_cover_switch_open','on') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.dummy_cover_switch_open
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.dummy_cover_switch_open
    dummy_cover_switch_close:
      friendly_name: "Close Cover"
      value_template: "{{ is_state('input_boolean.dummy_cover_switch_close','on') }}"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.dummy_cover_switch_close
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.dummy_cover_switch_close

# LIGHT
light:

- platform: template
  lights:
    dummy_light:
      friendly_name: "Light"
      turn_on:
        service: input_boolean.turn_on
        entity_id: input_boolean.dummy_light
      turn_off:
        service: input_boolean.turn_off
        entity_id: input_boolean.dummy_light
# COVER
cover:

- platform: cover_time_based
  devices:
    dummy_cover:
      name: "dummy_cover"
      travelling_time_down: 20
      travelling_time_up: 20
      open_switch_entity_id: switch.dummy_cover_switch_open
      close_switch_entity_id: switch.dummy_cover_switch_close