input_number:

  prova:
    name: "Prova"
    min: -6.000
    max: 6.000
    step: 0.001

sensor:

  - platform: template
    sensors:
      powerall_site_now:
        friendly_name: "Powerall Site Now"
        unit_of_measurement: 'KW'
        value_template: "{{ states('input_number.prova') }}"
      positive:
        friendly_name: "Positivo"
        unit_of_measurement: 'KW'
        value_template: "{{ 0 if states('sensor.powerall_site_now') | float < 0 else states('sensor.powerall_site_now') | float }}"
      negative:
        friendly_name: "Negativo"
        unit_of_measurement: 'KW'
        value_template: "{{ 0 if states('sensor.powerall_site_now') | float >= 0 else states('sensor.powerall_site_now') | float | abs }}"