# ENTITA' DI TEST

input_number:
  temperatura:
    name: Temperatura
    initial: 20
    min: 18
    max: 30
    step: 1

sensor:
  - platform: template
    sensors:
      termostato_temperatura:
        friendly_name: "Termostato Temperatura"
        value_template: "{{ states('input_number.temperatura') | float(2) }}"

# Entità per gestire una luce fake
# L'input boolean serve per tenere lo stato dell'entità di tipo light
# creata con platform template

input_boolean:
  termostato:

switch:
  - platform: template
    switches:
      termostato_interruttore:
        friendly_name: "Termostato Interruttore"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.termostato
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.termostato

# Questa è la tua automazione (ho usato gli stessi nomi che hai tu)

climate:

- platform: generic_thermostat
  name: Termostato
  heater: switch.termostato_interruttore
  target_sensor: sensor.termostato_temperatura
  min_temp: 15
  max_temp: 21
  ac_mode: false
  target_temp: 17
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
    seconds: 5
  keep_alive:
    minutes: 3
  initial_hvac_mode: "off"
  away_temp: 16
  precision: 0.1