sensor:

- platform: template
  sensors:
    giorni_nel_mese:
      friendly_name: "Giorni nel mese"
      value_template: >
        {% if now().month in [1,3,5,7,8,10,12] %}
          31
        {% elif now().month in [4,6,9,11] %}
          30
        {% elif now().month == 2 and ((now().year-2000) % 4 > 0) %}
          28
        {% elif now().month == 2 and ((now().year-2000) % 4 == 0) %}
          29
        {% endif %}